# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: en-AU
reviews:
  profile: assertive
  request_changes_workflow: true
  high_level_summary: true
  auto_review:
    enabled: true
    drafts: false
